export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
